# Collector configuration
mon.collectors.cpu.CpuInfo:
  interval: 20
  
mon.collectors.dnsmasq.DnsMasqDhcpInfo:
  interval: 60
  
mon.collectors.dnsmasq.DnsMasqDnsInfo:
  interval: 60
  
mon.collectors.hostapd.HostapdInfo:
  interval: 20
  
mon.collectors.net.NetDeviceInfo:
  filter_devices: lo
  interval: 15
    
mon.collectors.storage.StorageInfo:
  interval: 30

mon.collectors.system.HostInfo:
  interval: 900

mon.collectors.system.MemoryInfo:
  interval: 30