# MQTT configuration
global:
  
  # hostname of the broker
  broker: opi2
  
  # MQTT port
  port: 1883
  
  # MQTT topic prefix
  prefix: mon

collectors:
  - class: mon.collectors.system.LoadAvg
    interval: 4

